color: orange
fieldLayouts:
  7b97ad99-7f37-403e-9c9f-7430674332d9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d2cbf44a-1143-41b0-bfae-41425f0c83a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5ffbb91d-3f87-49fb-a024-4b482a2f6597 # Naam
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8fa56b3-2c3d-4113-a56b-562c4021ee1b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0bcf9f44-8f09-44f9-a164-57b6e1739f92 # Beschrijving
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee118b83-e5c8-4bb6-b618-2580b192b422
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7062f3b1-6205-4495-9522-f44a901a7617 # Concert
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57cc5bb4-c922-4109-80f8-b6db187ac995
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a5ea3a1a-a81b-458a-abfb-0135588dacd1 # Artiest Afbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b3a73da-d300-4679-b4f5-a076c3ead093
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ae1affce-49d8-4dc4-a117-1af17e857802
        userCondition: null
handle: artiest
hasTitleField: true
icon: person
name: Artiest
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
