color: red
fieldLayouts:
  2ced6b99-35a7-4f21-9ed5-fe21d8aa3723:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f0f39a46-cb1d-40a8-8451-183c75f54c80
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5ffbb91d-3f87-49fb-a024-4b482a2f6597 # Naam
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae55ba43-43db-4987-9083-f519693b0a44
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 51542f65-0505-4f4a-88ca-d6ef21e3aa87 # Adres
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cc42bc5-77fe-4d42-b78a-53a0d721321d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0bcf9f44-8f09-44f9-a164-57b6e1739f92 # Beschrijving
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 668c7005-231a-469a-bc27-3cc940c4d00c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 41268559-ba7f-46a9-ad60-faa218febf2f # Locatie Afbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92f3fe80-7943-4752-bbc3-69f302a0abbe
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 52798e18-a1ad-4035-8282-81a55270dce1
        userCondition: null
handle: locatie
hasTitleField: true
icon: location-dot
name: Locatie
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
