altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  384c1f5f-6207-4c0a-a337-c9f76a135e47:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e44ff6f0-c3d0-4de8-8447-36030d35a43d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 537de6d4-d289-4fdb-b6d5-c53047b0d59a
        userCondition: null
fs: artiest
handle: artiestImage
name: 'Artiest Image'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
