columnSuffix: null
handle: prijs
instructions: null
name: Prijs
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: EUR
  previewFormat: currency
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
