defaultPlacement: end
enableVersioning: true
entryTypes:
  - 45911286-29d0-43c9-953f-ea35ec247732 # Locatie
  - ecbcb4da-44bc-4c49-8a85-60ba5786fea6 # Concert
handle: locaties
maxAuthors: 1
name: Locaties
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  4271f66b-661b-4326-b80d-a20475e29b30: # echoflow
    enabledByDefault: true
    hasUrls: true
    template: locaties/_entry
    uriFormat: 'locaties/{slug}'
type: channel
